### ISSUE TITLE
Don't use get_playlist() to determine the admin pages to render

### ISSUE THREAD

**Issue by stevegrunwell** [awesomemotive/wp101plugin#81]
Currently, [`WP101\Admin\register_menu_pages()` includes a call to `Api::get_playlist()`](https://github.com/101videos/wp101plugin/blob/develop/includes/admin.php#L76) to determine whether or not there are videos to show. However, the `get_playlist()` call is intentionally only cached for a minute, to reduce lag between adding add-ons and them becoming visible within WP Admin.

As a result, the plugin is making a ton of unnecessary requests to the WP101 Plugin SaaS (effectively once/minute whenever someone's in WP Admin), which also bumps the "Last seen" date for the API key even though the site owner may not have been doing anything related to WP101.

To get around this, we should use a different conditional to determine whether or not to load the playlist page that updates far less frequently.

**Comment by awps** [comment]
Fixed in 5.4.0
